from . import product
from . import stock_lot
from . import res_partner
from . import insurance_plan
from . import pos_order
from . import pos_order_line
from . import pos_order_line
from . import insurance_lines
from . import pos_make_payment
from . import account_move
